# Generated by Django 4.1.7 on 2023-03-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
